-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 18:28:23 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Progent_Usuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Progent_Usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Progent_Usuarios` DEFAULT CHARACTER SET utf8mb3 ;
USE `Progent_Usuarios` ;

-- -----------------------------------------------------
-- Table `Progent_Usuarios`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progent_Usuarios`.`Usuarios` (
  `Correos` VARCHAR(200) NOT NULL,
  `SALT` VARCHAR(32) NULL,
  `Hashed` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Correos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;
ALTER TABLE Usuarios
ADD CONSTRAINT formato_correo
CHECK(REGEXP_LIKE(Correos, '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'));


-- -----------------------------------------------------
-- Table `Progent_Usuarios`.`informacion_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progent_Usuarios`.`informacion_usuarios` (
  `Correos` VARCHAR(200) NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Edad` INT NOT NULL,
  `Telefono` VARCHAR(50) NOT NULL,
  `Correo_contacto` VARCHAR(200) NOT NULL,
  `Experiencia` LONGTEXT NOT NULL,
  `Educacion` LONGTEXT NOT NULL,
  `Titulos` LONGTEXT NOT NULL,
  PRIMARY KEY (`Correos`),
  CONSTRAINT `Correos`
    FOREIGN KEY (`Correos`)
    REFERENCES `Progent_Usuarios`.`Usuarios` (`Correos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Progent_Usuarios` ;

-- -----------------------------------------------------
-- procedure verificar_usuario
-- -----------------------------------------------------

DELIMITER $$
USE `Progent_Usuarios`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `verificar_usuario`(IN Correo VARCHAR(200), OUT mensaje ENUM('Usuario Disponible', 'Usuario No Disponible'))
BEGIN
IF EXISTS (SELECT 1 FROM usuarios WHERE Correos = Correo) THEN
SET mensaje = 'Usuario No Disponible';
ELSE
SET mensaje = 'Usuario Disponible';
END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
